name: Deploy Backend to MonsterASP

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore Backend/el3omda.sln

    - name: Build project
      run: dotnet build Backend/el3omda.sln --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish Backend/WebApi/WebApi.csproj --configuration Release --no-build --output ./publish

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish/
        server-dir: /wwwroot/